version: '3.9'

services:
  revanced:
    image: nikhilbadyal/docker-py-revanced
    container_name: revanced-builder
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - .:/app:z
