name: Push to DockerHub
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
      - 'README.md'
jobs:
  dockerhub-push:
    uses: nikhilbadyal/ghactions/.github/workflows/dockerhub-push.yml@main
    if: github.repository == 'nikhilbadyal/docker-py-revanced'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  cleanup:
    name: GitHub Cleanup
    uses: nikhilbadyal/ghactions/.github/workflows/github-cleanup.yml@main
    with:
      PLATFORMS: linux/amd64
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
