name: Run Checks for PR
# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
on:
  workflow_dispatch:
  pull_request:

jobs:
  linter:
    uses: ./.github/workflows/linter.yml
  build-apk:
    uses: ./.github/workflows/build-apk-artifact.yml
